include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_element: warning
    unused_field: warning
    unused_import: warning
    unused_local_variable: warning
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    # Performance Rules
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - sized_box_shrink_expand

    # Safety & Quality Rules
    - use_build_context_synchronously
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - depend_on_referenced_packages
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - empty_catches
    - no_duplicate_case_values
    - valid_regexps

    # Clean Code Rules
    - avoid_unused_constructor_parameters
    - unnecessary_async
    - unnecessary_await_in_return
    - unnecessary_const
    - unnecessary_late
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_parenthesis
    - unnecessary_null_aware_assignments
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
