name: mechanix_widgets
description: "A collection of common and reusable Flutter widgets designed specifically for building Mechanix Apps with ease"
version: 0.0.1
homepage:

environment:
  sdk: ^3.6.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icon_font_generator: ^4.1.0

flutter:
  fonts:
    - family: MechanixIcons
      fonts:
        - asset: assets/fonts/MechanixIcons.ttf

icon_font_generator:
  from: assets/icons/svg
  out_font: assets/fonts/MechanixIcons.ttf
  out_flutter: lib/src/icons/mechanix_icons.dart
  class_name: MechanixIcons
  font_family: MechanixIcons
  package: mechanix_widgets
